const products = [
  {
    id: 1,
    img: "/images/silk/silkCategory.png",
    category: ["Silk Sarees",],
    tag: "New",
    discountPrice: 2899,
    actualPrice: 3699,
    rating: 4,
    ratings: "124",
  },
  {
    id: 2,
    img: "/images/cotton/cottonCategory.png",
    category: ["Cotton Sarees"],
    tag: "-20%",
    discountPrice: 3299,
    actualPrice: 4199,
    rating: 4,
    ratings: "98",
  },
  {
    id: 3,
    img: "/images/paithani/paithaniCategory.png",
    category: ["Paithani Sarees"],
    tag: "-10%",
    discountPrice: 2999,
    actualPrice: 3799,
    rating: 4,
    ratings: "87",
  },
  {
    id: 4,
    img: "/images/georgette/georgetteCategory.png",
    category: ["Georgette Sarees"],
    tag: "New",
    discountPrice: 1499,
    actualPrice: 1999,
    rating: 4,
    ratings: "64",
  },
  {
    id: 5,
    img: "/images/organza/organzaCategory.png",
    category: ["Organza Sarees"],
    tag: "New",
    discountPrice: 1299,
    actualPrice: 1999,
    rating: 4,
    ratings: "93",
  },
  {
    id: 6,
    img: "/images/silk/silk-1.jpg",
    category: ["Silk Sarees"],
    tag: "New",
    discountPrice: 2499,
    actualPrice: 3299,
    rating: 4,
    ratings: "128",
  },
  {
    id: 7,
    img: "/images/cotton/cotton-2.jpg",
    category: ["Cotton Sarees"],
    tag: "-15%",
    discountPrice: 1799,
    actualPrice: 2399,
    rating: 5,
    ratings: "96",
  },
  {
    id: 8,
    img: "/images/organza/organza-1.jpg",
    category: ["Organza Sarees"],
    tag: "New",
    discountPrice: 2199,
    actualPrice: 2899,
    rating: 4,
    ratings: "83",
  },
  {
    id: 9,
    img: "/images/georgette/georgette-3.jpg",
    category: ["Georgette Sarees"],
    tag: "-10%",
    discountPrice: 1699,
    actualPrice: 2299,
    rating: 4,
    ratings: "74",
  },
  {
    id: 10,
    img: "/images/paithani/paithani-1.jpg",
    category: ["Paithani Sarees"],
    tag: "sale",
    discountPrice: 5499,
    actualPrice: 6999,
    rating: 5,
    ratings: "156",
  },
  {
    id: 11,
    img: "/images/cotton/cotton-3.jpg",
    category: ["Cotton Sarees"],
    tag: "New",
    discountPrice: 1899,
    actualPrice: 2499,
    rating: 4,
    ratings: "118",
  },
  {
    id: 12,
    img: "/images/silk/silk-5.jpg",
    category: ["Silk Sarees", "Organza Sarees"],
    tag: "sale",
    discountPrice: 3499,
    actualPrice: 4299,
    rating: 5,
    ratings: "204",
  },
  {
    id: 13,
    img: "/images/georgette/georgette-2.jpg",
    category: ["Georgette Sarees"],
    tag: "New",
    discountPrice: 1699,
    actualPrice: 2199,
    rating: 4,
    ratings: "76",
  },
  {
    id: 14,
    img: "/images/paithani/paithani-4.jpg",
    category: ["Paithani Sarees", "Silk Sarees"],
    tag: "sale",
    discountPrice: 5999,
    actualPrice: 7599,
    rating: 5,
    ratings: "243",
  },
  {
    id: 15,
    img: "/images/organza/organza-3.jpg",
    category: ["Organza Sarees"],
    tag: "sale",
    discountPrice: 2399,
    actualPrice: 3099,
    rating: 4,
    ratings: "92",
  },
  {
    id: 16,
    img: "/images/silk/silk-6.jpg",
    category: ["Silk Sarees"],
    tag: "New",
    discountPrice: 2899,
    actualPrice: 3699,
    rating: 5,
    ratings: "165",
  },
  {
    id: 17,
    img: "/images/georgette/georgette-5.jpg",
    category: ["Georgette Sarees", "Organza Sarees"],
    tag: "-10%",
    discountPrice: 1799,
    actualPrice: 2399,
    rating: 4,
    ratings: "84",
  },
  {
    id: 18,
    img: "/images/cotton/cotton-6.jpg",
    category: ["Cotton Sarees", "Silk Sarees"],
    tag: "New",
    discountPrice: 2199,
    actualPrice: 2899,
    rating: 4,
    ratings: "131",
  },
  {
    id: 19,
    img: "/images/paithani/paithani-5.jpg",
    category: ["Paithani Sarees"],
    tag: "-25%",
    discountPrice: 6299,
    actualPrice: 8199,
    rating: 5,
    ratings: "221",
  },
  {
    id: 20,
    img: "/images/organza/organza-5.jpg",
    category: ["Organza Sarees", "Silk Sarees"],
    tag: "New",
    discountPrice: 2699,
    actualPrice: 3499,
    rating: 4,
    ratings: "109",
  },
  {
    id: 21,
    img: "/images/silk/silk-7.jpg",
    category: ["Silk Sarees"],
    tag: "New",
    discountPrice: 3199,
    actualPrice: 3999,
    rating: 5,
    ratings: "176",
  },
  {
    id: 22,
    img: "/images/cotton/cotton-7.jpg",
    category: ["Cotton Sarees", "Organza Sarees"],
    tag: "-15%",
    discountPrice: 2099,
    actualPrice: 2699,
    rating: 4,
    ratings: "97",
  },
  {
    id: 23,
    img: "/images/georgette/georgette-7.jpg",
    category: ["Georgette Sarees"],
    tag: "New",
    discountPrice: 1899,
    actualPrice: 2499,
    rating: 4,
    ratings: "112",
  },
  {
    id: 24,
    img: "/images/paithani/paithani-6.jpg",
    category: ["Paithani Sarees", "Silk Sarees"],
    tag: "Bestseller",
    discountPrice: 6599,
    actualPrice: 8399,
    rating: 5,
    ratings: "254",
  },
  {
    id: 25,
    img: "/images/organza/organza-6.jpg",
    category: ["Organza Sarees"],
    tag: "New",
    discountPrice: 2499,
    actualPrice: 3199,
    rating: 4,
    ratings: "106",
  },
  {
    id: 26,
    img: "/images/silk/silk-8.jpg",
    category: ["Silk Sarees", "Paithani Sarees"],
    tag: "-20%",
    discountPrice: 3799,
    actualPrice: 4699,
    rating: 5,
    ratings: "192",
  },
  {
    id: 27,
    img: "/images/georgette/georgette-8.jpg",
    category: ["Georgette Sarees", "Organza Sarees"],
    tag: "New",
    discountPrice: 1999,
    actualPrice: 2599,
    rating: 4,
    ratings: "88",
  },
  {
    id: 28,
    img: "/images/cotton/cotton-8.jpg",
    category: ["Cotton Sarees"],
    tag: "-10%",
    discountPrice: 2299,
    actualPrice: 2899,
    rating: 4,
    ratings: "138",
  },
  {
    id: 29,
    img: "/images/paithani/paithani-7.jpg",
    category: ["Paithani Sarees"],
    tag: "New",
    discountPrice: 6899,
    actualPrice: 8799,
    rating: 5,
    ratings: "267",
  },
  {
    id: 30,
    img: "/images/organza/organza-7.jpg",
    category: ["Organza Sarees", "Silk Sarees"],
    tag: "-25%",
    discountPrice: 2799,
    actualPrice: 3599,
    rating: 4,
    ratings: "121",
  },
  {
    id: 31,
    img: "/images/silk/silk-9.jpg",
    category: ["Silk Sarees"],
    tag: "New",
    discountPrice: 3999,
    actualPrice: 4999,
    rating: 5,
    ratings: "214",
  },
  {
    id: 32,
    img: "/images/cotton/cotton-9.jpg",
    category: ["Cotton Sarees", "Georgette Sarees"],
    tag: "-20%",
    discountPrice: 2399,
    actualPrice: 3099,
    rating: 4,
    ratings: "147",
  },
  {
    id: 33,
    img: "/images/georgette/georgette-9.jpg",
    category: ["Georgette Sarees"],
    tag: "New",
    discountPrice: 2099,
    actualPrice: 2799,
    rating: 4,
    ratings: "94",
  },
  {
    id: 34,
    img: "/images/paithani/paithani-8.jpg",
    category: ["Paithani Sarees", "Silk Sarees"],
    tag: "Bestseller",
    discountPrice: 7299,
    actualPrice: 9299,
    rating: 5,
    ratings: "281",
  },
  {
    id: 35,
    img: "/images/organza/organza-8.jpg",
    category: ["Organza Sarees"],
    tag: "New",
    discountPrice: 2899,
    actualPrice: 3699,
    rating: 4,
    ratings: "126",
  },
  {
    id: 36,
    img: "/images/silk/silk-10.jpg",
    category: ["Silk Sarees", "Organza Sarees"],
    tag: "-10%",
    discountPrice: 4299,
    actualPrice: 5399,
    rating: 5,
    ratings: "238",
  },
  {
    id: 37,
    img: "/images/georgette/georgette-10.jpg",
    category: ["Georgette Sarees", "Organza Sarees"],
    tag: "-15%",
    discountPrice: 2299,
    actualPrice: 2999,
    rating: 4,
    ratings: "102",
  },
  {
    id: 38,
    img: "/images/cotton/cotton-10.jpg",
    category: ["Cotton Sarees"],
    tag: "New",
    discountPrice: 2599,
    actualPrice: 3299,
    rating: 4,
    ratings: "158",
  },
  {
    id: 39,
    img: "/images/paithani/paithani-9.jpg",
    category: ["Paithani Sarees", "Silk Sarees"],
    tag: "-25%",
    discountPrice: 7599,
    actualPrice: 9699,
    rating: 5,
    ratings: "296",
  },
  {
    id: 40,
    img: "/images/organza/organza-9.jpg",
    category: ["Organza Sarees", "Georgette Sarees"],
    tag: "New",
    discountPrice: 3099,
    actualPrice: 3899,
    rating: 4,
    ratings: "135",
  },
  {
    id: 41,
    img: "/images/silk/silk-2.jpg",
    category: ["Silk Sarees"],
    tag: "New",
    discountPrice: 3399,
    actualPrice: 4299,
    rating: 5,
    ratings: "184",
  },
  {
    id: 42,
    img: "/images/cotton/cotton-1.jpg",
    category: ["Cotton Sarees", "Silk Sarees"],
    tag: "-15%",
    discountPrice: 2199,
    actualPrice: 2899,
    rating: 4,
    ratings: "143",
  },
  {
    id: 43,
    img: "/images/georgette/georgette-1.jpg",
    category: ["Georgette Sarees"],
    tag: "New",
    discountPrice: 1799,
    actualPrice: 2399,
    rating: 4,
    ratings: "91",
  },
  {
    id: 44,
    img: "/images/paithani/paithani-10.jpg",
    category: ["Paithani Sarees", "Silk Sarees"],
    tag: "Bestseller",
    discountPrice: 7999,
    actualPrice: 9999,
    rating: 5,
    ratings: "322",
  },
  {
    id: 45,
    img: "/images/organza/organza-10.jpg",
    category: ["Organza Sarees"],
    tag: "New",
    discountPrice: 3199,
    actualPrice: 3999,
    rating: 4,
    ratings: "148",
  },
  {
    id: 46,
    img: "/images/silk/silk-3.jpg",
    category: ["Silk Sarees", "Organza Sarees"],
    tag: "-20%",
    discountPrice: 3599,
    actualPrice: 4499,
    rating: 5,
    ratings: "207",
  },
  {
    id: 47,
    img: "/images/cotton/cotton-4.jpg",
    category: ["Cotton Sarees"],
    tag: "New",
    discountPrice: 2099,
    actualPrice: 2699,
    rating: 4,
    ratings: "124",
  },
  {
    id: 48,
    img: "/images/georgette/georgette-4.jpg",
    category: ["Georgette Sarees", "Organza Sarees"],
    tag: "-10%",
    discountPrice: 1999,
    actualPrice: 2599,
    rating: 4,
    ratings: "109",
  },
  {
    id: 49,
    img: "/images/paithani/paithani-2.jpg",
    category: ["Paithani Sarees"],
    tag: "New",
    discountPrice: 6199,
    actualPrice: 7899,
    rating: 5,
    ratings: "246",
  },
  {
    id: 50,
    img: "/images/organza/organza-4.jpg",
    category: ["Organza Sarees", "Silk Sarees"],
    tag: "-25%",
    discountPrice: 2699,
    actualPrice: 3499,
    rating: 4,
    ratings: "132",
  },
  {
    id: 51,
    img: "/images/silk/silk-8.jpg",
    category: ["Silk Sarees"],
    tag: "New",
    discountPrice: 3899,
    actualPrice: 4899,
    rating: 5,
    ratings: "213",
  },
  {
    id: 52,
    img: "/images/cotton/cotton-9.jpg",
    category: ["Cotton Sarees", "Georgette Sarees"],
    tag: "Trending",
    discountPrice: 2399,
    actualPrice: 3099,
    rating: 4,
    ratings: "137",
  },
  {
    id: 53,
    img: "/images/georgette/georgette-6.jpg",
    category: ["Georgette Sarees"],
    tag: "New",
    discountPrice: 2199,
    actualPrice: 2899,
    rating: 4,
    ratings: "116",
  },
  {
    id: 54,
    img: "/images/paithani/paithani-6.jpg",
    category: ["Paithani Sarees", "Silk Sarees"],
    tag: "Premium",
    discountPrice: 6999,
    actualPrice: 8999,
    rating: 5,
    ratings: "341",
  },
  {
    id: 55,
    img: "/images/organza/organza-6.jpg",
    category: ["Organza Sarees"],
    tag: "New",
    discountPrice: 2999,
    actualPrice: 3799,
    rating: 4,
    ratings: "127",
  },
  {
    id: 56,
    img: "/images/silk/silk-9.jpg",
    category: ["Silk Sarees", "Paithani Sarees"],
    tag: "Bestseller",
    discountPrice: 4499,
    actualPrice: 5599,
    rating: 5,
    ratings: "271",
  },
  {
    id: 57,
    img: "/images/cotton/cotton-10.jpg",
    category: ["Cotton Sarees"],
    tag: "-15%",
    discountPrice: 2499,
    actualPrice: 3199,
    rating: 4,
    ratings: "152",
  },
  {
    id: 58,
    img: "/images/georgette/georgette-8.jpg",
    category: ["Georgette Sarees", "Organza Sarees"],
    tag: "New",
    discountPrice: 2399,
    actualPrice: 3099,
    rating: 4,
    ratings: "118",
  },
  {
    id: 59,
    img: "/images/paithani/paithani-3.jpg",
    category: ["Paithani Sarees"],
    tag: "Premium",
    discountPrice: 6599,
    actualPrice: 8499,
    rating: 5,
    ratings: "287",
  },
  {
    id: 60,
    img: "/images/organza/organza-8.jpg",
    category: ["Organza Sarees", "Georgette Sarees"],
    tag: "New",
    discountPrice: 3299,
    actualPrice: 4199,
    rating: 4,
    ratings: "164",
  },
];

export default products;